# Weatherbot for 

name: CI
on:
  schedule:
    - cron: '0 9-22/2 * * *'

  workflow_dispatch:
jobs:
  job1:
    environment: TEST_SECRET
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
      - run: pip install telebot
      - run: pip install requests
      - name: Start Weather bot
        run: python WeatherBot.py
        env:
          CHAT_ID2: ${{ secrets.CHAT_ID2 }}
          TELEGRAM_API_KEY: ${{ secrets.TELEGRAM_API_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
