# Weatherbot for 

name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
#   schedule:
#   - cron: "0 5-20/2 * * *" 

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install telebot
      - run: pip install requests
      - run: python WeatherBot.py
